--CREATE STAGE SQUEMA

CREATE DATABASE FOOD_ANALYTICS;
USE DATABASE FOOD_ANALYTICS;
CREATE SCHEMA RAW;
CREATE SCHEMA STAGING;FOOD_ANALYTICS.RAW

USE DATABASE FOOD_ANALYTICS;
USE SCHEMA RAW;

SELECT *
FROM RAW_DAVILAS
LIMIT 10;


--CREATE STAGE TABLES

CREATE OR REPLACE TABLE STAGING.STG_DAVILAS AS

SELECT

    SUCURSAL,

    TRY_TO_TIMESTAMP(
        CREACION_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS CREACION_ORDEN,

    TRY_TO_TIMESTAMP(
        ENTREGA_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS ENTREGA_ORDEN,

    ORDEN_CANCELADA,

    ESTATUS,

    TIPO_PAGO,

    TOTAL,

    PLATILLOS

FROM RAW.RAW_DAVILAS

WHERE CREACION_ORDEN != 'Creación de orden';


CREATE OR REPLACE TABLE STAGING.STG_BURRITOS AS

SELECT

    SUCURSAL,

    TRY_TO_TIMESTAMP(
        CREACION_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS CREACION_ORDEN,

    TRY_TO_TIMESTAMP(
        ENTREGA_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS ENTREGA_ORDEN,

    ORDEN_CANCELADA,

    ESTATUS,

    TIPO_PAGO,

    TOTAL,

    PLATILLOS

FROM RAW.RAW_BURRITOS
WHERE CREACION_ORDEN != 'Creación de orden';




CREATE OR REPLACE TABLE STAGING.STG_SUSHIGO AS

SELECT

    SUCURSAL,

    TRY_TO_TIMESTAMP(
        CREACION_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS CREACION_ORDEN,

    TRY_TO_TIMESTAMP(
        ENTREGA_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS ENTREGA_ORDEN,

    ORDEN_CANCELADA,

    ESTATUS,

    TIPO_PAGO,

    TOTAL,

    PLATILLOS

FROM RAW.RAW_SUSHIGO
WHERE CREACION_ORDEN != 'Creación de orden';


CREATE OR REPLACE TABLE STAGING.STG_TOTA AS

SELECT

    SUCURSAL,

    TRY_TO_TIMESTAMP(
        CREACION_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS CREACION_ORDEN,

    TRY_TO_TIMESTAMP(
        ENTREGA_ORDEN,
        'HH24:MI:SS DD-MM-YYYY'
    ) AS ENTREGA_ORDEN,

    ORDEN_CANCELADA,

    ESTATUS,

    TIPO_PAGO,

    TOTAL,

    PLATILLOS

FROM RAW.RAW_TOTA
WHERE CREACION_ORDEN != 'Creación de orden';


---UNITE TABLES
CREATE OR REPLACE TABLE ANALYTICS.ALL_ORDERS AS

SELECT * FROM STAGING.STG_DAVILAS

UNION ALL

SELECT * FROM STAGING.STG_SUSHIGO

UNION ALL

SELECT * FROM STAGING.STG_BURRITOS

UNION ALL

SELECT * FROM STAGING.STG_TOTA;

